/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      // Cloudinary is the production image store for everything uploaded via /studio.
      { protocol: 'https', hostname: 'res.cloudinary.com' },
      // Allowed so seeded demo content can point at remote placeholders if desired.
      { protocol: 'https', hostname: 'images.unsplash.com' },
    ],
    formats: ['image/avif', 'image/webp'],
    // Placeholder art and the procedural fabric swatches are SVG. They are all
    // generated by this repo (scripts/generate-placeholders.ts, lib/swatches.ts)
    // and never user-supplied, and the CSP below neuters scripting inside them.
    dangerouslyAllowSVG: true,
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },
  experimental: {
    serverActions: { bodySizeLimit: '4mb' },
  },
};

export default nextConfig;
